apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: container1
    image: nginx
    ports:
    - containerPort: 8080
  - name: container2
    image: afakharany/watcher:latest
    ports:
    - containerPort: 8080
